# Generated by Django 6.0.3 on 2026-05-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('crane_type', models.CharField(choices=[('standard_pf', 'Standard PF Crane'), ('pf_xxl', 'PF-XXL')], max_length=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('crane_torque_max', models.FloatField()),
                ('crane_torque_nom', models.FloatField()),
                ('worm_ratio', models.FloatField()),
                ('worm_efficiency', models.FloatField()),
                ('motor_speed', models.FloatField()),
                ('motor_rated_torque', models.FloatField()),
                ('starting_factor', models.FloatField()),
                ('gearbox_output_speed', models.FloatField()),
                ('supplier_motor_power_kw', models.FloatField(blank=True, null=True)),
                ('supplier_motor_rated_torque', models.FloatField(blank=True, null=True)),
                ('supplier_motor_starting_torque', models.FloatField(blank=True, null=True)),
                ('supplier_gearbox_rated_torque', models.FloatField(blank=True, null=True)),
                ('supplier_bevel_ratio', models.FloatField(blank=True, null=True)),
                ('supplier_worm_ratio', models.FloatField(blank=True, null=True)),
                ('torque_check', models.CharField(max_length=20)),
                ('torque_margin', models.FloatField()),
                ('motor_power_kw', models.FloatField()),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
