# Generated by Django 6.0.3 on 2026-05-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcalculation',
            name='crane_torque_nom',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
