# Generated by Django 6.0.3 on 2026-05-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_motorcalculation_crane_torque_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcalculation',
            name='price_prototype',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='price_series',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
