# Generated by Django 6.0.3 on 2026-05-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_motorcalculation_price_prototype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_ambient_temp',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_coating',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_cooling_method',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_duty_cycle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_frame_material',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_heater',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_insulation_class',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_ip_rating',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_motor_certificate',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_output_flange',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_painting',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_shaft',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_top_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='motorcalculation',
            name='spec_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
